#!/usr/bin/env ruby

require 'optparse'
require 'gimp'
require 'gimp/options'
require 'yaml'
require 'hashie/mash'

options = Gimp::Options.new(File.exist?('.gimp') ? YAML.load_file('.gimp') : {})
options.parse!(ARGV)
if options.version?
  puts Gimp::VERSION
  exit
elsif options.help? || !options.valid?
  puts options.usage
  exit
end

mover = Gimp::Mover.new(options)
options.issues.each do |id|
  new_id = mover.move_issue(id)
  puts "#{options.source}##{id} -> #{options.destination}##{new_id}"
end
